version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres-container
    networks:
      - app_network
    environment:
      POSTGRES_USER: bestuser
      POSTGRES_PASSWORD: bestuser
      POSTGRES_DB: my_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-container
    networks:
      - app_network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/my_db
      SPRING_DATASOURCE_USERNAME: bestuser
      SPRING_DATASOURCE_PASSWORD: bestuser
    ports:
      - "30030:8080"
    restart: always

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data: